appuio/component-openshift4-monitoring

- .github/workflows/test.yaml
- .gitignore
- CHANGELOG.md
- Makefile
- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- docs/modules/ROOT/partials/nav.adoc
- playbook.yml
> Initial implementation

- CHANGELOG.md
- docs/modules/ROOT/pages/index.adoc
> Document usage of infra nodes

- CHANGELOG.md
- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
> Configure user workload monitoring defaults

- CHANGELOG.md
- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
Based on #4 
Relates to https://github.com/projectsyn/commodore/pull/192
> Remove deprecated parameters

- CHANGELOG.md
- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Configure AlertManager

- CHANGELOG.md
- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
> Enable storage for AlertManager by default

- Makefile
The `Makefile` was created from an older version of the Commodore component template. This change updates it to the latest version.
> Update Makefile from component template

- CHANGELOG.md
- Makefile
- class/defaults.yml
- class/openshift4-monitoring.yml
- component/main.jsonnet
- component/rules.jsonnet
- docs/modules/ROOT/pages/explanations/alert_rules.adoc
- docs/modules/ROOT/pages/index.adoc
- docs/modules/ROOT/pages/references/parameters.adoc
- jsonnetfile.json
> Ability to manage alert rules

- CHANGELOG.md
- class/defaults.yml
- component/main.jsonnet
- component/silence.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Ensure silence in Alertmanager using a CronJob

- CHANGELOG.md
- docs/modules/ROOT/pages/how-tos/opsgenie.adoc
- docs/modules/ROOT/partials/nav.adoc
> Add how-to for sending alerts to OpsGenie

- CHANGELOG.md
- class/defaults.yml
- component/rules.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Add support to annotate AlertRules

- .sync.yml
> Setup `.sync.yml` for modulesync

- .sync.yml
- tests/release-4.7.yml
- tests/release-4.8.yml
> Enable CI tests

- .github/workflows/test.yaml
- .sync.yml
- class/defaults.yml
- class/openshift4-monitoring.yml
- tests/release-4.9.yml
Diff between 4.8 and 4.9: https://gist.github.com/bastjan/fa57becf0bc957c93ae8733562943696
> Add manifests for OCP version 4.9

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- lib/prom.libsonnet
> Add option to add additional rules

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
> Fix outdated user workload monitoring configuration

- .sync.yml
- class/defaults.yml
- class/openshift4-monitoring.yml
- tests/release-4.10.yml
> Add definitions and test for release 4.10

- class/defaults.yml
- component/silence.jsonnet
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/golden/release-4.7/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/golden/release-4.8/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/silence.yaml
> Run silence cronjobs on infra nodes

- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
> Pull changes from upstream to golden tests

- class/defaults.yml
- component/capacity.libsonnet
- docs/modules/ROOT/pages/runbooks/cpucapacity.adoc
- docs/modules/ROOT/pages/runbooks/memorycapacity.adoc
- docs/modules/ROOT/pages/runbooks/podcapacity.adoc
- docs/modules/ROOT/pages/runbooks/resourcerequests.adoc
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
As discussed in https://github.com/appuio/component-openshift4-monitoring/pull/101
> Remove configurable threshold from defaults.yml

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
> Add support for configuring Thanos object storage

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- class/defaults.yml
- class/openshift4-monitoring.yml
- component/rules.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/rbac.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/release-4.11.yml
> Support for OCP 4.11

- class/defaults.yml
- component/main.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml
- tests/release-4.11.yml
> Allow generating secrets in component

- class/defaults.yml
- component/scripts/silence.sh
- component/silence.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/silence.yaml
> Make silences configurable

- class/defaults.yml
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/user-workload-monitoring.yml
> Enable user workload monitoring by default

- docs/modules/ROOT/pages/references/alert-patching.adoc
> Actually add documentation page for alertpatching lib

- class/defaults.yml
- docs/modules/ROOT/pages/runbooks/remotewrite.adoc
- docs/modules/ROOT/partials/nav.adoc
- tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
> Add runbook for PrometheusRemoteWrite alerts

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- class/openshift4-monitoring.yml
- component/rules.jsonnet
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/rbac.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/vsphere.yml
The alert rules are only rendered for fact `cloud=vsphere`.
changelog.
> Download and render vsphere-problem-detector alertrules

- component/main.jsonnet
- tests/capacity-alerts-with-node-labels.yml
- tests/capacity-alerts.yml
- tests/es-operator-rules.yml
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/release-4.10.yml
- tests/release-4.11.yml
- tests/release-4.9.yml
- tests/remote-write.yml
- tests/user-workload-monitoring.yml
- tests/vsphere.yml
> Use `patch-operator.libsonnet` directly

- .cruft.json
- .github/workflows/test.yaml
- Makefile.vars.mk
- component/capacity.libsonnet
- lib/openshift4-monitoring-alert-patching.libsonnet
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/rbac.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/team-label.yml
> Inject `syn_team` label for all alerts

- class/defaults.yml
- component/rules.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
> Disable low-value alerts by default

- class/defaults.yml
- component/rules.jsonnet
- docs/modules/ROOT/pages/references/parameters.adoc
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
> Add support for customizing alert rule namespace selector

- tests/custom-rules.yml
- tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/user-workload-monitoring.yml
- tests/vsphere.yml
> Switch remaining non-release-specific test cases to OCP 4.13

- class/defaults.yml
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
> Add `cluster_id` external label for UWM Prometheus

- component/main.jsonnet
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/user-workload-monitoring.yml
> Fix params.defaultConfig overwriting customisations

- class/defaults.yml
- jsonnetfile.jsonnet
- renovate.json
See syntax errors in https://github.com/kubernetes/kube-state-metrics/pull/2388 for why this was created.
changelog.
> Use stable version of `kube-state-metrics`

- component/networkpolicy.libsonnet
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
> Fix alertmanager-allow-web networkpolicy

- class/defaults.yml
- class/openshift4-monitoring.yml
- tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/rbac.yaml
- tests/golden/release-4.18/openshift4-monitoring/openshift4-monitoring/silence.yaml
- tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
- tests/release-4.18.yml
> Openshift monitoring 4.18
