CHANGELOG.md, component/rules.jsonnet
Recording rules cannot have field annotations, so we exclude them when adding our custom annotations. We identify recording rules by the absence of field alert in the rule object.
=> Skip recording rules when adding custom annotations

class/defaults.yml
quay.io purges unreferenced image layers. Having a fixed sha here will
brake things sooner or later.
=> Remove SHA from image tag

CHANGELOG.md, component/main.jsonnet, docs/modules/ROOT/pages/how-tos/migrate/v0.1-v1.x.adoc, docs/modules/ROOT/partials/nav.adoc
This PR changes the component to not make the `openshift-monitoring` namespace object itself managed by Syn ArgoCD.
This change ensures that deactivating the component on a cluster will not delete the whole OpenShift cluster-monitoring component.
Instead, the component now uses the resource-locker component to add the desired labels to the existing namespace object.
Additionally, since changing the namespace value for the component doesn't make sense at the moment, an error is printed if a value other than `openshift-monitoring` is detected for `parameters.openshift4_monitoring.namepace`.
Fixes #24
=> Change component to not "take over" the openshift-monitoring namespace

CHANGELOG.md, class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
This PR adds the parameter `enableUserWorkload` to allow [monitoring for user-defined projects](https://docs.openshift.com/container-platform/4.7/monitoring/enabling-monitoring-for-user-defined-projects.html).
=> User defined monitoring

component/rules.jsonnet
This prevents catalog commits where the only change is reordered alert rules.
=> Sort Rules by name

class/defaults.yml, component/rules.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
This allows us to adjust upstream rules which we want to keep but which need some tuning.
This feature can be used by adding the desired change for a rule in local variable `rulePatches` with the upstream rule name as the key.
=> Add support for patching upstream rules

class/openshift4-monitoring.yml
The cluster autoscaler operator project dropped the rules to check if the operator is down.
See https://github.com/openshift/cluster-autoscaler-operator/commit/7bbbe7233421b7e13f7dd82bc2553d64b3d7641c.
=> Drop inclusion of removed alert rules

class/defaults.yml, class/openshift4-monitoring.yml, component/rules.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
This code add the capablity to switch the rules between the
network plugins openshift-sdn and ovn-kubernetes.
Further it also add the exclude capability for not always required
rules of the Cluster Sample, Logging and ElasticSearch operators.
=> Add the capability to exclude upstream rules

class/defaults.yml, class/openshift4-monitoring.yml, component/rules.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
Prometheus rules for cluster logging are added to the openshift4-logging component.
=> Remove cluster logging prometheus rules

class/openshift4-monitoring.yml, docs/modules/ROOT/pages/references/parameters.adoc
Download always both network plugin rules sets of openshift-sdn and
ovn-kubernetes. Given any other values, will ignore both rules sets
from being applied.
=> Support custom network plugins

component/main.jsonnet
Withouth the label `syn=true` the alerts will be automatically silenced
=> Add missing label for custom alerts

component/main.jsonnet
=> The syn label should be set on the alert itself

class/defaults.yml, component/capacity.libsonnet, component/main.jsonnet, docs/modules/ROOT/pages/explanations/resource_management.adoc, docs/modules/ROOT/pages/references/parameters.adoc, docs/modules/ROOT/pages/runbooks/cpucapacity.adoc, docs/modules/ROOT/pages/runbooks/memorycapacity.adoc, docs/modules/ROOT/pages/runbooks/podcapacity.adoc, docs/modules/ROOT/pages/runbooks/resourcerequests.adoc, docs/modules/ROOT/partials/nav.adoc
This PR adds capacity planing alerts. It adds alerts for pod count as well as CPU/memory requests and actual utilization for worker nodes.
The actual alerts might need some tweaking, but should be easily done through the parameters.
This took a lot longer than anticipated and I probably went a bit overboard, but I did not want to throw in some half baked alerts.
=> Add resource management alerts

class/defaults.yml, component/capacity.libsonnet
The default thresholds are always the value of the largest worker node. It is helpful to alert if we reach the threshold of multiple nodes without having to replace the complete threshold
=> Add option to multiply the default thresholds for capacity alerts

component/capacity.libsonnet
With #85 we introduced factors for the capacity alert thresholds. These factors should be floats not integers.
=> Handle non integer factors for capacity alerts

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc
If required, these alerts can be enabled by choice on a cluster. As a baseline, the
standard non-predictive alerts are enough.
This reduces the amount of tenant data written.
=> Disable predictive capacity alerts by default

component/main.jsonnet, component/rbac.libsonnet, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/rbac.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/rbac.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/rbac.yaml
RedHat fix a permission bug we were (ab-)using. We now need to explicitly give the prometheus instance permission to list all pods, services, and endpoints. See https://issues.redhat.com/browse/LOG-2286
=> Give prometheus permissions to auto-discover targets

component/main.jsonnet
=> Allow removing remote write configs by setting them to `null`

component/silence.jsonnet, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/silence.yaml
On fresh OpenShift 4.11 installations, the `prometheus-k8s` ServiceAccount has `automountServiceAccountToken=false` which prevents automatic creation of the projected SA token volume. On upgraded clusters, this configuration for the ServiceAccount isn't updated.
This commit updates the silence cronjob to have an explicit projected SA token volume which should resolve the issue of the cronjob failing to find the SA token on fresh 4.11 installations.
=> Explicitly configure projected SA token volume for silence cronjob

.cruft.json, .github/workflows/test.yaml, Makefile.vars.mk, class/defaults.yml, component/rules.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/rbac.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/user-workload-monitoring.yml
Don't inherit the full cluster-monitoring config but reuse the cluster-monitoring volumeClaimTemplates for prometheus and alertmanager. Additionally, add support for patching out the user workload monitoring in `job=` and `namespace=` selectors in  `expr` and `annotations.description` of alerting rules. This allows users to silence noisy user workload monitoring alerts (e.g. for bad rule or alert routing configurations created by users).
Replaces #127 
=> Clean up user workload monitoring default config

component/aggregated-clusterroles.libsonnet, component/main.jsonnet, docs/modules/ROOT/pages/index.adoc, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml
We add a custom clusterrole which is aggregated to `cluster-reader` which grants `get`, `list`, `watch` on all `monitoring.coreos.com` resources. This should allow users which have cluster-reader look at Prometheus rules, ServiceMonitors etc. without having to impersonate cluster-admin.
=> Aggregate `monitoring.coreos.com` objects to `cluster-reader`

class/defaults.yml, tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Go 1.18/ Kubernetes 1.24 adjusted how memory is freed on systems with enough free memory. Adjust alert to be less sensitive.
See https://bugzilla.redhat.com/show_bug.cgi?id=2074031.
> In Kubernetes 1.24 and later versions, the response latency is reduced by 10 times for 99% of the API requests handled by kube-apiserver and the loads of kube-apiserver increase by about 25%. This is because Kubernetes 1.24 is compiled with Go 1.18, which has significant changes in its garbage collection algorithm. If the memory usage increase of kube-apiserver is not acceptable, you can mitigate the impacts by setting the GOGC environment variable. You can specify GOGC=63 to bring the memory usage of kube-aspiserver back to the original level.
https://www.alibabacloud.com/help/en/container-service-for-kubern …
=> Adjust HighOverallControlPlaneMemory alert on OCP4.11

class/defaults.yml, component/rules.jsonnet, docs/modules/ROOT/partials/nav.adoc, lib/openshift4-monitoring-alert-patching.libsonnet, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
The library provides functions `patchRule()`, `filterRules()` and `filterPatchRules()`. The functions are documented using doxygen-style comments which have been manually transferred to an asciidoc reference page.
We also use the new library to render our own alerting rules. This injects `syn_component: openshift4-monitoring` to all alerts rendered by this component.
Relates to https://github.com/appuio/component-openshift4-logging/issues/64
=> Provide component library with functions for alert patching and filtering

class/defaults.yml, tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
This is a follow-up to #137, the patched alert rule isn't rolled out due to failing ArgoCD sync:
```
error validating data: ValidationError(PrometheusRule.spec.groups[12].rules[0]): unknown field "description" in com.coreos.monitoring.v1.PrometheusRule.spec.groups.rules
```
=> Fix patch for HighOverallControlPlaneMemory alert rule

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/silence.yaml
=> Enable non-predictive capacity alerts by default 

.cruft.json, .github/workflows/test.yaml, Makefile.vars.mk, class/defaults.yml, component/capacity.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/capacity-alerts-with-node-labels.yml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/90_syn_monitoring.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/rbac.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml
With this change, we can give a list of node labels to the component to make it segregate the generated capacity alerts by node label. If the list is empty (default), the generated alerts are functionally equivalent to before.
My change in the alert generation logic caused all alerts to change slightly, but the resulting metrics are equivalent. I only removed no-op relabelings, and in some expressions where relabeling is actually required, I moved it to the other side of the operator (e.g. instead of relabeling `node` to `instance` on the LHS, I'm relabeling `instance` to `node` on the RHS).
changelog.
as they show up in …
=> Add support for grouping capacity alerts by node label

component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/es-operator-rules/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/release-4.10/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/release-4.9/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/01_secrets.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/remote-write.yml
This PR allows us to configure remote write for the user workload monitoring stack. Works the same way as the feature introduced in https://github.com/appuio/component-openshift4-monitoring/pull/125.
As context we'd like to use this as AppCat collects some metrics through the user-workload monitoring stack to allow users to define their own alerting rules, but we'd still like to ship some of these metrics to central monitoring.
changelog.
=> Allow remoteWrite for user workload monitoring to be configured in hierarchy

component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/remote-write.yml
=> Add option to configure timeseries as a list instead of regex in relabel config

component/rules.jsonnet, docs/modules/ROOT/pages/references/alert-patching.adoc, lib/openshift4-monitoring-alert-patching.libsonnet
We also remove the previous code which injects
`alerts.customAnnotations` in `rules.jsonnet`, since we call `patchRule()` for each alert managed through this component anyway.
changelog.
=> Add support for `alerts.customAnnotations` in the alert-patching library

.cruft.json, .github/workflows/test.yaml, Makefile.vars.mk, component/main.jsonnet, docs/modules/ROOT/pages/references/alert-patching.adoc, docs/modules/ROOT/pages/references/prom.adoc, docs/modules/ROOT/partials/nav.adoc, lib/openshift4-monitoring-prom.libsonnet, tests/custom-rules.yml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/00_namespace_labels.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/02_aggregated_clusterroles.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/capacity_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/custom_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/rbac.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/silence.yaml
This PR introduces a new library function which allows other components to provide the same interface as this component's `rules` parameter without having to reimplement the same Jsonnet to transform the input format into valid `PrometheusRule`
manifests.
The PR also refactors the rule rendering for this component, and adds a test case for rule rendering.
changelog.
=> Add new library function `generateRules()` to render custom `PrometheusRule` objects

class/defaults.yml, component/rules.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc
The parameter is not needed anymore with parameter `alerts.ignoreGroups`, where we ignore the `SamplesOperator` group by default.
Follow-up to #159 
changelog.
=> Remove parameter `upstreamRules.clusterSamplesOperator`

component/scripts/silence.sh, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/silence.yaml
In the rare case that a node clock isn't properly synchronized, the new silence can start slightly after the existing one is already expired. This leads to unnecessary alerts. 
changelog.
=> Add 1min time overlap for silence cronjob

lib/openshift4-monitoring-alert-patching.libsonnet, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/custom_rules.yaml, tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/team-label.yml
=> Respect existing `syn_team` labels when patching alerts

lib/openshift4-monitoring-alert-patching.libsonnet, tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/custom_rules.yaml, tests/team-label.yml
=> Correctly handle alerts with no labels

class/defaults.yml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
Allow to work with more human friendly values on dashboards.
changelog.
=> Add cluster and tenant names to external labels

class/defaults.yml, component/main.jsonnet, component/networkpolicy.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/team-label/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml
Alertmanager sometimes did build a cluster with customer installed AMs or the user workload monitoring AMs.
changelog.
=> Block gossip traffic between alertmanagers in different namespaces

lib/openshift4-monitoring-alert-patching.libsonnet
Tested to work both in component jsonnet and post-process jsonnet with a recent commodore version.
changelog.
=> Allow using alert patching library in post process filters

lib/openshift4-monitoring-prom.libsonnet, tests/team-routing.yml
=> Allow removing instances from `syn.teams`

component/alert-routing-discovery.libsonnet, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml, tests/team-routing.yml
Sorts and deduplicates the namespaces.
changelog.
=> Make alert routing discovery output easier to review

docs/modules/ROOT/pages/references/parameters.adoc, docs/modules/ROOT/pages/references/prom.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
=> Fix formatting in component docs

docs/modules/ROOT/pages/references/parameters.adoc
=> Replace dead link to Alertmanager config reference

class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap_user_workload.yaml, tests/remote-write.yml
=> Allow setting remote write default parameters

component/alert-routing-discovery.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/team-routing.yml
This allows us to gradually roll out Alertmanager configs with new fields set (e.g. `opsgenie_configs.source` in a receiver config) even though the receiver config is formatted as a list which isn't easily editable in the hierarchy.
changelog.
=> Prune fields with `null` values in user-provided Alertmanager config

component/scripts/silence.sh, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/silence.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/silence.yaml
The cronjob renews the silence every 4 hours. I don't see any added benefits in creating silences with 1 year lifetime instead of one day.
However there is one major downside. If the silence functionality is used to suppress certain alerts temporarily, the silence stays active for 1 year after it's removed from the config hierarchy. To enable the alert again it, the silence has to be expired manually on all clusters.
Reducing this to one day is a compromise that allows to remove silences and ensure they're active again in a reasonable timeframe without having to manually  expire all silences. Happy to discuss other values for the duration.
changelog.
`bug`, `enhancement`, `documentation`, …
=> Expire silences after one day instead of one year

class/defaults.yml, component/cronjobs.libsonnet, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/custom-rules.yml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/cronjobs.yaml
=> Add support for deploying arbitrary cronjobs

class/openshift4-monitoring.yml, component/rules.jsonnet
OpenShift 4.14 moved the OVNKubernetes control plane alerts (and we can't use the 4.13 alerts, because 4.14 makes significant changes to the OVNKubernetes architecture). Additionally 4.14 introduced gotemplate snippets in the OVNKubernetes alerts that we need to render.
Since the files also contain gotemplate snippets which aren't valid Jinja2, we implement very simple rendering logic which uses `std.strReplace()` in the component.
changelog.
=> Fix OVNKubernetes alert rules for OpenShift 4.14

component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.11/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.12/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
This allows us to remove configurations from the cluster-monitoring-config in the hierarchy.
changelog.
=> Prune cluster-monitoring-config contents

.cruft.json, class/defaults.yml, component/custom-node-exporter.libsonnet, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, renovate.json, tests/custom-rules.yml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/appuio_node_exporter.yaml
We reuse the cluster-monitoring-operator node-exporter Jsonnet to generate the DaemonSet and associated resources, and patch the output to adjust the node-exporter to not conflict with the default node-exporter and to remove resources that we don't need.
Additionally, we enable automerge for the 3rd party container images used by the component.
changelog.
=> Add support for deploying an additional node-exporter DaemonSet

class/defaults.yml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Adjust the alert to fire when there's >100*cores major page faults on a node instead of >500.
changelog.
=> Tune `NodeMemoryMajorPageFaults` alert

component/rules.jsonnet, docs/modules/ROOT/pages/runbooks/tcp-memory-usage.adoc, docs/modules/ROOT/partials/nav.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.13/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Add alert which fires when TCP memory utilization on a node exceeds the configured kernel-level TCP memory "pressure" threshold. (6.25% on RHEL8/RHEL9). Add an alert runbook which contains all the debugging snippets we've discovered so far.
changelog.
=> Add alert for high TCP memory utilization on nodes

component/rules.jsonnet
Some upstream Jsonnet hides the `runbook_url` annotation on alerts.
Because of that, some of our patches which insert the `runbook_url` annotation don't work correctly with go-jsonnet 0.20.0, which correctly inherits field visibility in object comprehension (e.g. `com.makeMergeable()`). This behavior will also be fixed in an upcoming C++ jsonnet version, cf. https://github.com/google/jsonnet/pull/1140 so we adjust the component to make all `runbook_url` annotations visible.
Notably, the upstream Jsonnet which hides the annotation also sets it to `null`, so we can then clean up the unwanted `runbook_url: null` annotations by calling `std.prune()` on the annotations object.
changelog.
`bug`, …
=> Make hidden `runbook_url` annotations visible

class/defaults.yml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml
Checked against internal cluster telemetry, seems to be a high fidelity alert. Only very few alerts need to be silenced due to operator managed PDBs.
changelog.
=> Enable `PodDisruptionBudgetAtLimit` alert to find maintenance blocking PDBs

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
This ensures that the new metrics-server component of the cluster monitoring stack has the default configs (e.g. node selector) applied.
changelog.
=> Add config section `metricsServer`

component/networkpolicy.libsonnet, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.14/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.15/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_networkpolicy.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/20_user_workload_networkpolicy.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/user-workload-monitoring.yml
This should fix the currently dropped connections from the HAProxy ingress controller to alertmanager.
changelog.
=> Allow traffic from cluster nodes to all workloads in the monitoring namespace

component/alert-routing-discovery.libsonnet, jsonnetfile.jsonnet, lib/openshift4-monitoring-alert-patching.libsonnet, lib/openshift4-monitoring-prom.libsonnet, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml, tests/team-routing.yml
This PR switches the alert routing discovery and alert patching to use the new `syn-teams.libsonnet` Jsonnet library. This library is hosted at https://github.com/projectsyn/jsonnet-libs and is intended to be used by all components which interact with `parameters.syn.owner` and `parameters.syn.teams`.
changelog.
=> Use `syn-teams.libsonnet` for alert routing discovery and alert patching

class/defaults.yml, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.17/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
We remove the unknown field `grafana` from cluster-monitoring-config defaults, because OpenShift 4.17 prints the following warning in `oc adm upgrade` when the `grafana` field is present in the `cluster-monitoring-config` configmap:
```
Message: Cluster operator monitoring should not be upgraded between minor versions: configuration in the "openshift-monitoring/cluster-monitoring-config" ConfigMap is invalid and should be fixed: error unmarshaling JSON: while decoding JSON: json: unknown field "grafana"
```
Additionally, we add the missing fields `monitoringPlugin` and `prometheusOperatorAdmissionWebhook` so that those components also get the default node-selector config and remove the <=4.15 field `prometheusAdapter`.
changelog.
The PR has a meaningful description that sums up the …
=> Update fields of `cluster-monitoring-config` for OpenShift 4.16 and newer

class/defaults.yml, component/main.jsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/custom-rules.yml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/release-4.17/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/10_configmap.yaml
The fields `nodeSelector` and `prometheusOperatorAdmissionWebhook` don't support field `nodeSelector`, so we don't list them in `class/defaults.yml` and don't apply the default config if a user provides them.
When the fields are present, a informational message is emitted noting that the default config isn't applied to the fields.
Fixes #232 
changelog.
=> Don't apply default config for `cluster-monitoring-config` fields which don't support `nodeSelector`

component/alert-routing-discovery.libsonnet, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.17/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/team-routing.yml
The alert routing discovery logic collects all namespaces referenced in component instances assigned to each team. Until now, we didn't consider the case where all instances assigned to a team would reference no namespaces. In such a case the discovery would generate a routing rule such as
```
- "continue": true
"matchers":
- "syn_team = \"\""
- "namespace =~ \"\""
"receiver": "team_default_<teamname>"
```
This PR adjusts the namespace discovery to drop team to namespace map entries whose values are empty or null.
changelog.
=> Fix alert routing discovery when no namespaces are discovered for a team

component/alert-routing-discovery.libsonnet, docs/modules/ROOT/pages/references/parameters.adoc, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/capacity-alerts/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/ovn-kubernetes/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.16/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/release-4.17/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/10_alertmanager_config.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/99_discovery_debug_cm.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/prometheus_rules.yaml, tests/team-routing.yml
We tend to use `namespace: ${_instance}` for components where we deploy each instance in a separate namespace (e.g. component-vault, component-openshift4-operators). However, because we read the instance namespaces from openshift4-monitoring's parameters, `${_instance}` is resolved to `openshift4-monitoring` and not to the component instance name.
This commit updates the discovery logic to override the discovered namespace if we discover a namespace that contains
`openshift4-monitoring` for any app other than `openshift4-monitoring` itself. The new override logic replaces all occurrences of `openshift4-monitoring` in the discovered namespace with the parsed component instance name.
changelog. …
=> Fix alert routing namespace discovery logic

class/defaults.yml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/40_oprules_global.yaml, tests/golden/capacity-alerts-with-node-labels/openshift4-monitoring/openshift4-monitoring/50_rules_additional.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/40_oprules_global.yaml, tests/golden/custom-rules/openshift4-monitoring/openshift4-monitoring/50_rules_additional.yaml, tests/golden/defaults/openshift4-monitoring/openshift4-monitoring/40_oprules_global.yaml, tests/golden/defaults/openshift4-monitoring/openshift4-monitoring/50_rules_additional.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/40_oprules_global.yaml, tests/golden/remote-write/openshift4-monitoring/openshift4-monitoring/50_rules_additional.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/40_oprules_global.yaml, tests/golden/team-routing/openshift4-monitoring/openshift4-monitoring/50_rules_additional.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/40_oprules_global.yaml, tests/golden/user-workload-monitoring/openshift4-monitoring/openshift4-monitoring/50_rules_additional.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/40_oprules_global.yaml, tests/golden/vsphere/openshift4-monitoring/openshift4-monitoring/50_rules_additional.yaml
We had the old version of this alert (`node_cpu_load5`) in the list of ignored alerts (probably because we forgot that we deployed it ourselves). Since it got renamed for v7.0.0, it didn't get dropped anymore.
Instead of updating the ignore list, we simply remove the custom alert rule completely.
Tagged as a `bug` because this restores v6 default behavior.
changelog.
=> Remove previously silenced `NodeCpuLoad5` alert
